# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\x12\x05video\"\x1d\n\x0c\x46rameRequest\x12\r\n\x05\x66rame\x18\x01 \x01(\t\"\x1f\n\rFrameResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2I\n\x0bVideoStream\x12:\n\x0bStreamFrame\x12\x13.video.FrameRequest\x1a\x14.video.FrameResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAMEREQUEST']._serialized_start=22
  _globals['_FRAMEREQUEST']._serialized_end=51
  _globals['_FRAMERESPONSE']._serialized_start=53
  _globals['_FRAMERESPONSE']._serialized_end=84
  _globals['_VIDEOSTREAM']._serialized_start=86
  _globals['_VIDEOSTREAM']._serialized_end=159
# @@protoc_insertion_point(module_scope)
