# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import video_pb2 as video__pb2


class VideoStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamFrame = channel.unary_unary(
                '/video.VideoStream/StreamFrame',
                request_serializer=video__pb2.FrameRequest.SerializeToString,
                response_deserializer=video__pb2.FrameResponse.FromString,
                )


class VideoStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamFrame(self, request, context):
        """Definindo o método para enviar frames
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.StreamFrame,
                    request_deserializer=video__pb2.FrameRequest.FromString,
                    response_serializer=video__pb2.FrameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'video.VideoStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VideoStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/video.VideoStream/StreamFrame',
            video__pb2.FrameRequest.SerializeToString,
            video__pb2.FrameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
